### PR TITLE
Remove sections having no questions in chosen chapters

### PR DESCRIPTION
**Pull request by Jayashrri**
Fixes issue #31 
In the table to select the number of questions from each question type, hides those sections which have no questions for the selected chapters

### CODE REVIEW

**Comment by ishanisri** [comment]
I am sorry but this is not what we meant by the issue. We ask the user to enter the number of questions to be present in the generic paper,so we cannot assume it from before. 

This issue is to remove the sections from generated question papers for which 0 questions had been chosen by the user.

This is the currently generated question paper.



And we want it to be like this, removing sections for which there are 0 questions.

**Comment by ishanisri** [comment]
This is not what the issue meant. We cannot remove sections before the user has selected the number of questions needed in each question.  I am closing this issue as the description is vague. Work on #31 instead.

**Comment by ishanisri** [comment]
Revert this commit and start again. Also, edit the name of the PR and make it clear and simple so that it self explains the objective it tries to achieve.

**Comment by Jayashrri** [comment]
Alright, I understood. Sorry for misunderstanding the issue.

**Pull request closed without merging**
